replicaCount: 1

app:
  name: new-app   # <--- THIS MUST MATCH your deployment

image:
  repository: docker.io/prathmeshwake/new-app
  tag: latest

service:
  port: 8080

activeColor: blue  # if you use blue/green switching
