replicaCount: 1

app:
  name: new-app

image:
  repository: docker.io/prathmeshwake/new-app
  tag: latest

service:
  port: 8080

activeColor: blue  # for blue/green

serviceAccount:
  create: false
  name: ""
